# Generated by Django 5.2.11 on 2026-02-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Course',
        ),
    ]
