# Generated by Django 5.2.11 on 2026-02-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_program_course'),
        ('attendance', '0001_initial'),
        ('faculty', '0002_facultymember_teacher_id_facultymember_user'),
        ('students', '0003_replace_course_charfield_with_fk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to='faculty.facultymember'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'subject', 'date')},
        ),
    ]
